# Generated by Django 3.1.4 on 2020-12-20 08:18

import BookStore.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('From', models.EmailField(default='', max_length=100)),
                ('Subject', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SellBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-img.jpg', upload_to=BookStore.models.get_upload_path)),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(default='subject', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='description', max_length=300)),
                ('college_name', models.CharField(default='college_name', max_length=200)),
                ('book_university', models.CharField(default='university', max_length=200)),
                ('seller_name', models.CharField(default='seller_name', max_length=200)),
                ('contact', models.CharField(default='contact', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='no-img.jpg', upload_to=BookStore.models.get_upload_path)),
                ('address', models.CharField(default='address', max_length=200)),
                ('city', models.CharField(default='city', max_length=100)),
                ('pincode', models.IntegerField(default='00')),
                ('state', models.CharField(default='state', max_length=100)),
                ('phone', models.IntegerField(default='0')),
                ('university_name', models.CharField(default='university', max_length=200)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('postal_zip', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.sellbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
