# Generated by Django 3.1.4 on 2020-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbook',
            name='contact',
        ),
        migrations.AddField(
            model_name='sellbook',
            name='seller_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='book_university',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='college_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='seller_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
